Repository Another-Glass/Assignment4_Team, pull requests merged in 2021-11, with the labels that each got.

#8 [feat]: 유저 회원가입 로직 추가
  src/controllers/userController.js
  src/models/account.js
  src/models/user.js
  src/services/userService.js
Labels: :fire: Feat, :man: :computer: 동훈, :man: :computer: 상수

#9 [feat]: 로그인 API 추가
  src/controllers/userController.js
  src/routes/userRouter.js
  src/services/userService.js
Labels: :fire: Feat, :man: :computer: 동훈

#10 [fix]: 로그인 서비스 버그 수정
  src/services/userService.js
Labels: :hammer_and_wrench: Fix, :man: :computer: 동훈

#7 [feat]: 계좌생성 API 추가
  src/controllers/accountController.js
  src/globals/responseMessage.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/models/account.js
  src/routes/accountRouter.js
  src/services/accountService.js
Labels: :fire: Feat, :man: :computer: 동훈, :man: :computer: 상수

#11 [feat]: 입출금 API, 서비스 기초 뼈대 구성
  src/controllers/accountController.js
  src/controllers/transactionController.js
  src/controllers/userController.js
  src/globals/responseMessage.js
  src/libs/jwt.js
  src/routes/accountRouter.js
  src/services/accountService.js
  src/services/transactionService.js
  src/services/userService.js
  src/utils/errors/transactionError.js
Labels: :fire: Feat, :hammer_and_wrench: Fix

#12 [Chore]: 깃허브 PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :star: Chore

#13 [fix]: 입출금 구현 및 버그수정
  src/controllers/accountController.js
  src/controllers/transactionController.js
  src/globals/responseMessage.js
  src/libs/jwt.js
  src/middlewares/auth.js
  src/services/accountService.js
  src/services/transactionService.js
  src/utils/errors/transactionError.js
  src/utils/logger.js
Labels: :hammer_and_wrench: Fix

#14 [fix]: 외래키 이름 불일치 수정
  src/controllers/transactionController.js
  src/models/account.js
  src/models/transaction.js
  src/utils/errors/transactionError.js
Labels: :hammer_and_wrench: Fix

#15 [fix]: 회원가입 서비스 버그 수정
  src/services/userService.js
Labels: :lady_beetle: Bug, :hammer_and_wrench: Fix, :man: :computer: 동훈

#16 [feat]: 유저 회원가입 단위 테스트
  src/package.json
  src/test/data/dto/signup.json
  src/test/unit/controllers/userController/postUser.test.js
Labels: :fire: Feat, :man: :computer: 상수

#17 [fix]: 입출금 비밀번호 확인 및 버그 수정
  src/controllers/transactionController.js
  src/services/accountService.js
  src/services/transactionService.js
  src/utils/errors/commonError.js
Labels: :hammer_and_wrench: Fix

#19 [fix]: Unit 테스트 시 발생한 ReferenceError 문제 해결
  src/models/index.js
  src/package.json
  src/test/unit/controllers/userController/postUser.test.js
Labels: :hammer_and_wrench: Fix, :man: :computer: 동훈

#20 [feat]: 유저 로그인 단위 테스트
  src/controllers/userController.js
  src/test/data/dto/signup.json
  src/test/unit/controllers/userController/postToken.test.js
Labels: :fire: Feat, :man: :computer: 상수

#22 [fix]: 계좌생성 ValidationError 코드 잘못된 부분 수정
  src/controllers/accountController.js
Labels: :hammer_and_wrench: Fix, :man: :computer: 동훈

#23 [fix]: 에러핸들링 추가
  src/controllers/accountController.js
  src/database.db
  src/middlewares/auth.js
  src/models/index.js
  src/utils/errors/tokenError.js
Labels: :hammer_and_wrench: Fix

#25 [feat]: 계좌 생성 단위 테스트
  src/middlewares/auth.js
  src/test/data/dto/postAccount.json
  src/test/data/dto/token.json
  src/test/unit/controllers/accountController/postAccount.test.js
Labels: :fire: Feat, :man: :computer: 상수

#28 [feat]: 입출금 API 단위테스트
  src/test/unit/controllers/transactionController/postTransaction.test.js
Labels: :fire: Feat, :man: :computer: 상수

#29 [fix]: 구문오류 수정, db예시파일 추가
  database.db
  src/configs/db.js
  src/controllers/accountController.js
  src/controllers/transactionController.js
  src/middlewares/auth.js
  src/models/index.js
  src/services/transactionService.js
Labels: :hammer_and_wrench: Fix

#32 [feat]: 거래내역 조회 API 단위 테스트
  src/test/unit/controllers/transactionController/getTransaction.test.js
  src/test/unit/controllers/transactionController/postTransaction.test.js
Labels: :fire: Feat, :man: :computer: 상수
